#version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_task4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
volumes:
  pgdata:

networks:
  postgres:
    driver: bridge