spring:
  application:
    name: Spring Security & JWT
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: secretkeyhellosecretkey123secretkeyhellosecretkey123
  tokenExpiration: 5m
  refreshTokenExpiration: 30m